# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform :android do

  before_all do
    ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/firebase_login_credentials.json"
    ENV["FIREBASE_APP_ID"] = "1:269966259407:android:2f3838a98e2c0b2609f3ba"
    ENV["FLAVOR_NAME"] = ""
  end

  ######## FIREBASE DISTRIBUTION  ########
  desc "Submit a new Google Test Build to Firebase App Distribution"
  lane :testGoogle do
     gradle(task: "clean")
     gradle(task: "assemble", flavor: ENV["FLAVOR_NAME"], build_type: "Release")

      # find apk path
     output_path = "./app/build/outputs/apk/"+ ENV["FLAVOR_NAME"]+"/release/"
     output_path = "./app/build/outputs/apk/release/"
     output_json_path = output_path + "output-metadata.json"
     build_output = load_json(json_path: output_json_path)
     elements = build_output["elements"][0]
     apk_path = output_path + elements["outputFile"]

     firebase_app_distribution(
           app: ENV["FIREBASE_APP_ID"],
           apk_path: apk_path,
          # firebase_cli_token: "1//0g8H6_l2PZOT0CgYIARAAGBASNwF-L9IrCwKxvLLfiTZe4fROSWfxu3ZcniIgpG05FSVCYBARyJvRNE0IK_zLxeJsurrWbqqCtIc",
           groups_file: "fastlane/groups.txt",
           release_notes_file:"fastlane/relasenotes.txt",
           service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
           debug: true
     )
     #firebase_cli_token: "1//0g8H6_l2PZOT0CgYIARAAGBASNwF-L9IrCwKxvLLfiTZe4fROSWfxu3ZcniIgpG05FSVCYBARyJvRNE0IK_zLxeJsurrWbqqCtIc",
  end

end